### ISSUE TITLE
migration command issue

### ISSUE THREAD

**Issue by ILLISIS** [Hornwitser/eternity_commands#3]
ubuntu@vps-b975be37:~/clusterio$ npx clusterioctl ec migrate --instances "Steel Smelting 17" --to-hosts eu14-node1

+==========================================================+
I WARNING:  This is the development branch for the 2.0     I
I           version of clusterio.  Expect things to break. I
+==========================================================+

[fatal] 
+------------------------------------------------------------+
| Unexpected error occured while starting control, please    |
| report it to https://github.com/clusterio/clusterio/issues |
+------------------------------------------------------------+
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.strict)(targetCommand instanceof lib.Command)

    at startControl (/home/ubuntu/clusterio/node_modules/@clusterio/ctl/dist/node/ctl.js:216:25)

**Comment by Hornwitser** [comment]
Thanks, fixed it in 04517b5
